- name: Ensure root password is set
  uri:
    url: "{{ base_url }}/system/users/root"
    method: PUT
    headers:
      token: "{{ api_token }}"
    body_format: json
    body:
      user:
        password: "{{ ansible_password }}"
        confirm_password: "{{ ansible_password }}"
    validate_certs: false
    return_content: true
    timeout: 10
  register: password_update
  failed_when: false

- name: Show password API response
  debug:
    var: password_update
  
- name: Set hostname
  uri:
    url: "{{ base_url }}/system/hostname"
    method: PUT
    headers:
      token: "{{ api_token }}"
    body_format: json
    body:
      system_hostname:
        #hostname: "{{ inventory_hostname }}"
        hostname: "{{ device_hostname }}"
    validate_certs: false

- name: Get WWAN config
  command: ogcli get physif wwan0
  register: wwan_config
  changed_when: false
  failed_when: false

- name: Set APN if needed
  shell: |
    ogcli update physif wwan0 << EOF
    cellular_setting.apn="{{ apn }}"
    EOF
  when: apn not in wwan_config.stdout

- name: Enable WWAN0 if needed
  command: ogcli update physif wwan0 enabled=true
  when: "'enabled = true' not in wwan_config.stdout"

- name: Wait for modem (non-fatal)
  pause:
    seconds: 5